// GENERATED by scripts/billing/build-admin-standalone.mjs; edit canonical sources only.
// Helper para acessar EXCLUSIVAMENTE o banco externo do usuário
// (syyxnqzxqabeuqbuptkh). Quando a function roda no projeto Lovable Cloud,
// usa EXTERNAL_*; quando roda diretamente no projeto externo, usa SUPABASE_*.
import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";

// Permite sobrescrever via secret EXTERNAL_PROJECT_REF; mantém o valor
// histórico como fallback para não quebrar deploys existentes.
const EXTERNAL_PROJECT_REF = Deno.env.get("EXTERNAL_PROJECT_REF") ?? "syyxnqzxqabeuqbuptkh";

function required(name: string): string {
  const v = Deno.env.get(name);
  if (!v) {
    throw new Error(
      `[external-supabase] secret ${name} não configurado. Configure-o em Settings → Secrets para apontar ao projeto externo (syyxnqzxqabeuqbuptkh).`,
    );
  }
  return v;
}

export function getExternalSupabaseUrl(): string {
  const external = Deno.env.get("EXTERNAL_SUPABASE_URL");
  if (external?.includes(EXTERNAL_PROJECT_REF)) return external;

  const nativeUrl = Deno.env.get("SUPABASE_URL");
  if (nativeUrl?.includes(EXTERNAL_PROJECT_REF)) return nativeUrl;

  // Evita registrar webhooks no projeto antigo quando EXTERNAL_SUPABASE_URL
  // ficou stale em Secrets. A URL pública do projeto é derivável pelo ref.
  return `https://${EXTERNAL_PROJECT_REF}.supabase.co`;
}

export function getExternalServiceRoleKey(): string {
  const external = Deno.env.get("EXTERNAL_SUPABASE_SERVICE_ROLE_KEY");
  if (external) return external;

  const nativeUrl = Deno.env.get("SUPABASE_URL");
  const nativeKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (nativeUrl?.includes(EXTERNAL_PROJECT_REF) && nativeKey) return nativeKey;

  return required("EXTERNAL_SUPABASE_SERVICE_ROLE_KEY");
}

export function getExternalAnonKey(): string {
  const external = Deno.env.get("EXTERNAL_SUPABASE_ANON_KEY");
  if (external) return external;

  const nativeUrl = Deno.env.get("SUPABASE_URL");
  const nativeKey = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  if (nativeUrl?.includes(EXTERNAL_PROJECT_REF) && nativeKey) return nativeKey;

  return required("EXTERNAL_SUPABASE_ANON_KEY");
}

/** Admin client (service role) apontando ao Supabase EXTERNO. */
export function getExternalAdmin(): SupabaseClient {
  return createClient(getExternalSupabaseUrl(), getExternalServiceRoleKey(), {
    auth: {
      persistSession: false,
    },
  });
}

/** Anon client usado para validar JWTs emitidos pelo Supabase EXTERNO. */
export function getExternalUserClient(): SupabaseClient {
  return createClient(getExternalSupabaseUrl(), getExternalAnonKey(), {
    auth: {
      persistSession: false,
    },
  });
}


// Shared helper to require an authenticated user with the 'admin' role
// (via the public.user_roles table). Returns a Response on failure, or
// the verified user id on success.
// ⚠️ Sempre opera no Supabase EXTERNO (banco principal do app).

export const adminCors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

export async function requireAdmin(req: Request): Promise<{ userId: string } | Response> {
  const authHeader = req.headers.get("Authorization") ?? "";
  if (!authHeader.toLowerCase().startsWith("bearer ")) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401, headers: { ...adminCors, "Content-Type": "application/json" },
    });
  }
  let admin;
  try {
    admin = getExternalAdmin();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Server misconfigured", detail: (e as Error).message }), {
      status: 500, headers: { ...adminCors, "Content-Type": "application/json" },
    });
  }
  const token = authHeader.replace(/^Bearer\s+/i, "");
  // Valida o JWT contra o próprio Supabase externo usando o service role do servidor.
  // Isso evita falso 401 quando a anon key usada para validação está ausente/rotacionada
  // nos secrets da Edge Function, sem reduzir a checagem de papel admin abaixo.
  const { data: userData, error: userErr } = await admin.auth.getUser(token);
  if (userErr || !userData?.user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401, headers: { ...adminCors, "Content-Type": "application/json" },
    });
  }
  const { data: roleRow } = await admin
    .from("user_roles")
    .select("role")
    .eq("user_id", userData.user.id)
    .eq("role", "admin")
    .maybeSingle();
  if (!roleRow) {
    return new Response(JSON.stringify({ error: "Forbidden" }), {
      status: 403, headers: { ...adminCors, "Content-Type": "application/json" },
    });
  }
  return { userId: userData.user.id };
}


// Edge function: gerenciamento manual de assinaturas pelo admin.
// Ações: list | audit | grant_plan | set_dates | start_trial | extend_trial |
//        renew | suspend | reactivate | cancel | update_note | clear_override

const jsonHeaders = { ...adminCors, "Content-Type": "application/json" };

function bad(msg: string, status = 400) {
  return new Response(JSON.stringify({ error: msg }), { status, headers: jsonHeaders });
}

function ok(data: unknown) {
  return new Response(JSON.stringify(data), { status: 200, headers: jsonHeaders });
}

function envName(): string {
  return "live";
}

interface Body {
  action: string;
  target_user_id?: string;
  plan_id?: string;
  product_id?: string;
  start_date?: string | null;
  end_date?: string | null;
  trial_days?: number;
  note?: string;
  status_filter?: string;
  search?: string;
  limit?: number;
  offset?: number;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: adminCors });
  if (req.method !== "POST") return bad("Method not allowed", 405);

  const guard = await requireAdmin(req);
  if (guard instanceof Response) return guard;
  const adminUserId = guard.userId;

  let body: Body;
  try { body = await req.json(); } catch { return bad("Invalid JSON"); }
  if (!body?.action) return bad("action required");

  const admin = getExternalAdmin();
  const env = envName();

  if (body.action === "list") {
    const { data, error } = await admin.rpc("billing_admin_list", {
      _admin: adminUserId, _env: env, _search: body.search ?? "", _status: body.status_filter ?? "",
      _limit: body.limit ?? 100, _offset: body.offset ?? 0,
    });
    if (error) return bad(error.message, 500);
    return ok(data);
  }

  // ---------------------- AUDIT ----------------------
  if (body.action === "audit") {
    if (!body.target_user_id) return bad("target_user_id required");
    const { data, error } = await admin
      .from("subscription_audit_log")
      .select("*")
      .eq("target_user_id", body.target_user_id)
      .order("created_at", { ascending: false })
      .limit(100);
    if (error) return bad(error.message, 500);
    return ok({ rows: data ?? [] });
  }

  if (!body.target_user_id) return bad("target_user_id required");
  const { data, error } = await admin.rpc("billing_admin_action", {
    _admin: adminUserId, _env: env, _body: body,
  });
  if (error) return bad(error.message, 400);
  return ok(data);
});
