// This file is automatically generated. Do not edit it directly.
//
// IMPORTANTE: este módulo NÃO cria um segundo cliente. Ele apenas reexporta o
// cliente único definido em `userClient.ts` (banco externo do projeto). Dois
// clientes com a mesma storageKey causavam conflito de sessão no GoTrue e
// falhas de login no preview.
export {
  supabase,
  USER_SUPABASE_URL,
  USER_SUPABASE_PUBLISHABLE_KEY,
  USER_SUPABASE_STORAGE_KEY,
} from "./userClient";
